// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParlorPrediction.Persistence;

#nullable disable

namespace ParlorPrediction.Persistence.Migrations
{
    [DbContext(typeof(ParlorPredictionDbContext))]
    [Migration("20260629190530_AddOperationalProjectionLedgers")]
    partial class AddOperationalProjectionLedgers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.ConsumptionLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EventBalls")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<int>("SalesBalls")
                        .HasColumnType("int");

                    b.Property<int>("ServiceUsageBalls")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("SourceType", "SourceEntityId", "CreatedAtUtc");

                    b.ToTable("ConsumptionLedgers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConsumptionLedgers_EventBalls_NonNegative", "[EventBalls] >= 0");

                            t.HasCheckConstraint("CK_ConsumptionLedgers_SalesBalls_NonNegative", "[SalesBalls] >= 0");

                            t.HasCheckConstraint("CK_ConsumptionLedgers_ServiceUsageBalls_NonNegative", "[ServiceUsageBalls] >= 0");

                            t.HasCheckConstraint("CK_ConsumptionLedgers_SourceType_NotEmpty", "LEN(LTRIM(RTRIM([SourceType]))) > 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DailyDoughClosing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualUsedBalls")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("ClosingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CorrectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrectedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrectionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ForecastNeededBalls")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAtUtc");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("ClosingDate")
                        .IsUnique();

                    b.HasIndex("CorrectedByUserId");

                    b.HasIndex("WeekStartDate");

                    b.ToTable("DailyDoughClosings", null, t =>
                        {
                            t.HasCheckConstraint("CK_DailyDoughClosings_ActualUsedBalls_NonNegative", "[ActualUsedBalls] >= 0");

                            t.HasCheckConstraint("CK_DailyDoughClosings_ForecastNeededBalls_NonNegative", "[ForecastNeededBalls] >= 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BalledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("BallsPerCase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(12);

                    b.Property<DateOnly>("BatchDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("FermentationReadyDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsBalled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEventException")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVoided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalBalls")
                        .HasColumnType("int");

                    b.Property<int>("TotalCases")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DoughBatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughBatches_BalledState", "([IsBalled] = 0 AND [BalledAtUtc] IS NULL) OR ([IsBalled] = 1 AND [BalledAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_DoughBatches_BallsPerCase_Positive", "[BallsPerCase] > 0");

                            t.HasCheckConstraint("CK_DoughBatches_FermentationReadyDate", "DATEDIFF(day, [BatchDate], [FermentationReadyDate]) >= 2");

                            t.HasCheckConstraint("CK_DoughBatches_TotalBalls_Positive", "[TotalBalls] > 0");

                            t.HasCheckConstraint("CK_DoughBatches_TotalCases_Positive", "[TotalCases] > 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughBatchQualityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AttentionMarkedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOrBalledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DiscardReason")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("DiscardedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("MustUseByDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("OriginalDoughTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityBalls")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReballedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SourceDate")
                        .HasColumnType("date");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("CreatedOrBalledAt");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("MustUseByDate");

                    b.HasIndex("OriginalDoughTaskId");

                    b.HasIndex("ReballedAt");

                    b.HasIndex("SourceDate");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("DoughBatchQualityRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughBatchQualityRecords_AttentionState", "([CurrentStatus] <> 'Attention' OR [AttentionMarkedAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_DoughBatchQualityRecords_DiscardState", "([CurrentStatus] <> 'Discarded' OR ([DiscardedAt] IS NOT NULL AND [DiscardReason] IS NOT NULL))");

                            t.HasCheckConstraint("CK_DoughBatchQualityRecords_MustUseState", "([CurrentStatus] <> 'MustUseNextDay' OR [MustUseByDate] IS NOT NULL)");

                            t.HasCheckConstraint("CK_DoughBatchQualityRecords_QuantityBalls_Positive", "[QuantityBalls] > 0");

                            t.HasCheckConstraint("CK_DoughBatchQualityRecords_ReballedState", "([CurrentStatus] NOT IN ('Reballed', 'MustUseNextDay') OR [ReballedAt] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughDemandPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxDoughBalls")
                        .HasColumnType("int");

                    b.Property<int>("MinDoughBalls")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek", "IsActive");

                    b.HasIndex("DayOfWeek", "SourceName")
                        .IsUnique();

                    b.ToTable("DoughDemandPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughDemandPlans_MaxDoughBalls_NonNegative", "[MaxDoughBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughDemandPlans_MaxGreaterThanMin", "[MaxDoughBalls] >= [MinDoughBalls]");

                            t.HasCheckConstraint("CK_DoughDemandPlans_MinDoughBalls_NonNegative", "[MinDoughBalls] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("1fd39395-730e-45ff-bfbb-5200fd9a4e01"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Tuesday",
                            IsActive = true,
                            MaxDoughBalls = 60,
                            MinDoughBalls = 60,
                            SourceName = "Restaurant",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6de48f1d-a319-4d43-b98f-82561fe7ab02"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Wednesday",
                            IsActive = true,
                            MaxDoughBalls = 80,
                            MinDoughBalls = 60,
                            SourceName = "Restaurant",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("61a2fa90-e538-4af7-8c63-ef10e5d2ee03"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Thursday",
                            IsActive = true,
                            MaxDoughBalls = 100,
                            MinDoughBalls = 80,
                            SourceName = "Restaurant",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f2ea9a3e-5980-4d0f-bc0e-f0f576e69d04"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Thursday",
                            IsActive = true,
                            MaxDoughBalls = 150,
                            MinDoughBalls = 100,
                            SourceName = "Westport Farmers Market",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2855c63-f748-4a8d-a4b8-d35f6c645a05"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Friday",
                            IsActive = true,
                            MaxDoughBalls = 120,
                            MinDoughBalls = 80,
                            SourceName = "Rowayton Farmers Market",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("09d8b6c8-33df-4e7f-b1e8-e7de54370306"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Friday",
                            IsActive = true,
                            MaxDoughBalls = 250,
                            MinDoughBalls = 170,
                            SourceName = "Restaurant",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("825e3150-7db6-42d2-8d37-b881622c8e07"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Saturday",
                            IsActive = true,
                            MaxDoughBalls = 120,
                            MinDoughBalls = 100,
                            SourceName = "Ridgefield Farmers Market",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7d30f506-b486-40f2-9a38-8e3e6e16c908"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Saturday",
                            IsActive = true,
                            MaxDoughBalls = 120,
                            MinDoughBalls = 80,
                            SourceName = "Saturday Night",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8375c417-4f0c-45c0-b9c5-24d1b2ebaa09"),
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = "Sunday",
                            IsActive = true,
                            MaxDoughBalls = 95,
                            MinDoughBalls = 60,
                            SourceName = "Restaurant",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughInventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableBalls")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("NewBalls")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OldBalls")
                        .HasColumnType("int");

                    b.Property<int>("ReservedBalls")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UsedBalls")
                        .HasColumnType("int");

                    b.Property<int>("WasteBalls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DoughInventorySnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughInventorySnapshots_AvailableBalls_NonNegative", "[AvailableBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughInventorySnapshots_NewBalls_NonNegative", "[NewBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughInventorySnapshots_OldBalls_NonNegative", "[OldBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughInventorySnapshots_ReservedBalls_NonNegative", "[ReservedBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughInventorySnapshots_UsedBalls_NonNegative", "[UsedBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughInventorySnapshots_WasteBalls_NonNegative", "[WasteBalls] >= 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughLossRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DoughBatchQualityRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("LossDate")
                        .HasColumnType("date");

                    b.Property<string>("LossReason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ManagerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("QuantityLostBalls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DoughBatchQualityRecordId");

                    b.HasIndex("LossDate");

                    b.HasIndex("LossReason");

                    b.ToTable("DoughLossRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughLossRecords_QuantityLostBalls_Positive", "[QuantityLostBalls] > 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughPrepRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableBalls")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EventEstimatedBalls")
                        .HasColumnType("int");

                    b.Property<int>("HistoricalAverageBalls")
                        .HasColumnType("int");

                    b.Property<int>("MissingBalls")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("RecommendationDate")
                        .HasColumnType("date");

                    b.Property<int>("RecommendedCases")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedLoads")
                        .HasColumnType("int");

                    b.Property<int>("RequiredBalls")
                        .HasColumnType("int");

                    b.Property<bool>("ShouldBallDough")
                        .HasColumnType("bit");

                    b.Property<bool>("ShouldMakeDough")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("UsesShortFermentationException")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationDate");

                    b.ToTable("DoughPrepRecommendations", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughPrepRecommendations_AvailableBalls_NonNegative", "[AvailableBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughPrepRecommendations_EventEstimatedBalls_NonNegative", "[EventEstimatedBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughPrepRecommendations_HistoricalAverageBalls_NonNegative", "[HistoricalAverageBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughPrepRecommendations_MissingBalls_NonNegative", "[MissingBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughPrepRecommendations_RecommendedCases_NonNegative", "[RecommendedCases] >= 0");

                            t.HasCheckConstraint("CK_DoughPrepRecommendations_RecommendedLoads_NonNegative", "[RecommendedLoads] >= 0");

                            t.HasCheckConstraint("CK_DoughPrepRecommendations_RequiredBalls_NonNegative", "[RequiredBalls] >= 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughReballRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DoughBatchQualityRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ManagerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("MustUseByDate")
                        .HasColumnType("date");

                    b.Property<int>("QuantityBeforeReball")
                        .HasColumnType("int");

                    b.Property<int>("QuantityLostBalls")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRecoveredBalls")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReballDate")
                        .HasColumnType("date");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DoughBatchQualityRecordId");

                    b.HasIndex("ReballDate");

                    b.HasIndex("Result");

                    b.ToTable("DoughReballRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughReballRecords_LossMath", "[QuantityLostBalls] = [QuantityBeforeReball] - [QuantityRecoveredBalls]");

                            t.HasCheckConstraint("CK_DoughReballRecords_MustUseByDate", "([Result] <> 'PartialRecovered' OR [MustUseByDate] IS NOT NULL)");

                            t.HasCheckConstraint("CK_DoughReballRecords_QuantityBeforeReball_Positive", "[QuantityBeforeReball] > 0");

                            t.HasCheckConstraint("CK_DoughReballRecords_QuantityLostBalls_NonNegative", "[QuantityLostBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughReballRecords_QuantityRecoveredBalls_NonNegative", "[QuantityRecoveredBalls] >= 0");

                            t.HasCheckConstraint("CK_DoughReballRecords_RecoveredNotGreaterThanBefore", "[QuantityBeforeReball] >= [QuantityRecoveredBalls]");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughUsageTrace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BallsPerTray")
                        .HasColumnType("int");

                    b.Property<int>("BallsUsed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("SourceDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SourceDoughBatchQualityRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TrayCount")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Destination");

                    b.HasIndex("SourceDate");

                    b.HasIndex("SourceDoughBatchQualityRecordId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UsageDate");

                    b.ToTable("DoughUsageTraces", null, t =>
                        {
                            t.HasCheckConstraint("CK_DoughUsageTraces_BallsPerTray_Positive", "[BallsPerTray] > 0");

                            t.HasCheckConstraint("CK_DoughUsageTraces_BallsUsed_MatchesTrays", "[BallsUsed] = ([TrayCount] * [BallsPerTray])");

                            t.HasCheckConstraint("CK_DoughUsageTraces_SourceType_Allowed", "[SourceType] <> 'Discarded'");

                            t.HasCheckConstraint("CK_DoughUsageTraces_TrayCount_Positive", "[TrayCount] > 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.InventoryTransformationLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BallsDiscarded")
                        .HasColumnType("int");

                    b.Property<int>("BallsReclassified")
                        .HasColumnType("int");

                    b.Property<int>("BallsRecovered")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("SourceType", "SourceEntityId", "CreatedAtUtc");

                    b.ToTable("InventoryTransformationLedgers", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryTransformationLedgers_BallsDiscarded_NonNegative", "[BallsDiscarded] >= 0");

                            t.HasCheckConstraint("CK_InventoryTransformationLedgers_BallsReclassified_NonNegative", "[BallsReclassified] >= 0");

                            t.HasCheckConstraint("CK_InventoryTransformationLedgers_BallsRecovered_NonNegative", "[BallsRecovered] >= 0");

                            t.HasCheckConstraint("CK_InventoryTransformationLedgers_SourceType_NotEmpty", "LEN(LTRIM(RTRIM([SourceType]))) > 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.ManagerPrepRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("PrepItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("RecommendationDate")
                        .HasColumnType("date");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RecommendedBalls")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedCases")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedLoads")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PrepItemId");

                    b.HasIndex("RecommendationDate");

                    b.ToTable("ManagerPrepRecommendations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagerPrepRecommendations_RecommendedBalls_NonNegative", "[RecommendedBalls] >= 0");

                            t.HasCheckConstraint("CK_ManagerPrepRecommendations_RecommendedCases_NonNegative", "[RecommendedCases] >= 0");

                            t.HasCheckConstraint("CK_ManagerPrepRecommendations_RecommendedLoads_NonNegative", "[RecommendedLoads] >= 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.OperationalAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AfterPreviewJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ApprovedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeforeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedIntentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValidationWarningsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("DraftId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("OperationalAuditEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_OperationalAuditEntries_ActionType_NotEmpty", "LEN(LTRIM(RTRIM([ActionType]))) > 0");

                            t.HasCheckConstraint("CK_OperationalAuditEntries_ActorUserId_NotEmpty", "LEN(LTRIM(RTRIM([ActorUserId]))) > 0");

                            t.HasCheckConstraint("CK_OperationalAuditEntries_SourceText_NotEmpty", "LEN(LTRIM(RTRIM([SourceText]))) > 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.OperationalDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterPreviewJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ApprovedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeforeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DraftPayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DraftType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedIntentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValidationWarningsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("OperationalDrafts", null, t =>
                        {
                            t.HasCheckConstraint("CK_OperationalDrafts_CreatedBy_NotEmpty", "LEN(LTRIM(RTRIM([CreatedBy]))) > 0");

                            t.HasCheckConstraint("CK_OperationalDrafts_DraftType_NotEmpty", "LEN(LTRIM(RTRIM([DraftType]))) > 0");

                            t.HasCheckConstraint("CK_OperationalDrafts_SourceText_NotEmpty", "LEN(LTRIM(RTRIM([SourceText]))) > 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.PrepItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PrepStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PrepStationId");

                    b.ToTable("PrepItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("db143624-2528-4b32-9f57-a6946440c2dc"),
                            Code = "DOUGH",
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Base dough preparation item for pizza service.",
                            IsActive = true,
                            Name = "Dough",
                            PrepStationId = new Guid("8b1ccf87-1c7d-4f61-9d4c-511af6c37901"),
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.PrepStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PrepStations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b1ccf87-1c7d-4f61-9d4c-511af6c37901"),
                            Code = "PIZZA",
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Primary pizza preparation station.",
                            IsActive = true,
                            Name = "Pizza",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3c0a95b2-f91c-4b4e-88c2-c4a3cc6c06f3"),
                            Code = "BAR",
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bar preparation station.",
                            IsActive = true,
                            Name = "Bar",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f60a7166-0b1d-40af-9d30-f2d8c3e8f5fb"),
                            Code = "SALAD",
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salad preparation station.",
                            IsActive = true,
                            Name = "Salad",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0a8f8653-bda7-42ee-baad-e9b2449d5eb4"),
                            Code = "EXPO",
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expo preparation station.",
                            IsActive = true,
                            Name = "Expo",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d23f69bc-b4a9-4380-98ce-52d8fe74d2f8"),
                            Code = "GENERAL",
                            CreatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "General restaurant preparation station.",
                            IsActive = true,
                            Name = "General",
                            UpdatedAtUtc = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.PrepTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("DoughPrepRecommendationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PrepItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrepStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityCompleted")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRecommended")
                        .HasColumnType("int");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SourceDoughBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourcePrepTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("TaskDate")
                        .HasColumnType("date");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedRole");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("DoughPrepRecommendationId")
                        .IsUnique()
                        .HasFilter("[DoughPrepRecommendationId] IS NOT NULL");

                    b.HasIndex("PrepItemId");

                    b.HasIndex("PrepStationId");

                    b.HasIndex("SourceDoughBatchId");

                    b.HasIndex("SourcePrepTaskId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskDate");

                    b.HasIndex("TaskType");

                    b.ToTable("PrepTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrepTasks_CompletionState", "([Status] <> 'Completed' AND [CompletedAtUtc] IS NULL AND [CompletedByUserId] IS NULL) OR ([Status] = 'Completed' AND [CompletedAtUtc] IS NOT NULL AND [CompletedByUserId] IS NOT NULL AND [QuantityCompleted] > 0)");

                            t.HasCheckConstraint("CK_PrepTasks_QuantityCompleted_NonNegative", "[QuantityCompleted] >= 0");

                            t.HasCheckConstraint("CK_PrepTasks_QuantityRecommended_NonNegative", "[QuantityRecommended] >= 0");

                            t.HasCheckConstraint("CK_PrepTasks_TaskTypeUnit", "([TaskType] = 'GenericDough' AND [QuantityUnit] = 'Balls') OR ([TaskType] = 'MakeDoughLoad' AND [QuantityUnit] = 'FullLoads') OR ([TaskType] = 'BallDough' AND [QuantityUnit] = 'Balls')");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.ProductionLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BallsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("BallsDiscarded")
                        .HasColumnType("int");

                    b.Property<int>("BallsReballed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TotalBallsCreated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("SourceType", "SourceEntityId", "CreatedAtUtc");

                    b.ToTable("ProductionLedgers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductionLedgers_BallsCompleted_NonNegative", "[BallsCompleted] >= 0");

                            t.HasCheckConstraint("CK_ProductionLedgers_BallsDiscarded_NonNegative", "[BallsDiscarded] >= 0");

                            t.HasCheckConstraint("CK_ProductionLedgers_BallsReballed_NonNegative", "[BallsReballed] >= 0");

                            t.HasCheckConstraint("CK_ProductionLedgers_SourceType_NotEmpty", "LEN(LTRIM(RTRIM([SourceType]))) > 0");

                            t.HasCheckConstraint("CK_ProductionLedgers_TotalBallsCreated_NonNegative", "[TotalBallsCreated] >= 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.RestaurantEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowShortFermentation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EstimatedDoughBalls")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedPizzas")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalCalendarEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EventDate", "IsActive");

                    b.ToTable("RestaurantEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_RestaurantEvents_EstimatedDoughBalls_NonNegative", "[EstimatedDoughBalls] >= 0");

                            t.HasCheckConstraint("CK_RestaurantEvents_EstimatedPizzas_NonNegative", "[EstimatedPizzas] >= 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.SalesHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DoughBallsUsed")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ProductName");

                    b.HasIndex("SaleDate");

                    b.ToTable("SalesHistories", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalesHistories_DoughBallsUsed_NonNegative", "[DoughBallsUsed] >= 0");

                            t.HasCheckConstraint("CK_SalesHistories_QuantitySold_NonNegative", "[QuantitySold] >= 0");
                        });
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.WeeklyDoughClosing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CorrectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrectedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrectionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("LeftoverAttentionBalls")
                        .HasColumnType("int");

                    b.Property<int>("LeftoverMixedLoads")
                        .HasColumnType("int");

                    b.Property<int>("LeftoverReadyBalls")
                        .HasColumnType("int");

                    b.Property<int>("LostBalls")
                        .HasColumnType("int");

                    b.Property<int>("NeededBalls")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProducedBalls")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UsedBalls")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WeekEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAtUtc");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CorrectedByUserId");

                    b.HasIndex("WeekStartDate")
                        .IsUnique();

                    b.ToTable("WeeklyDoughClosings", null, t =>
                        {
                            t.HasCheckConstraint("CK_WeeklyDoughClosings_LeftoverAttentionBalls_NonNegative", "[LeftoverAttentionBalls] >= 0");

                            t.HasCheckConstraint("CK_WeeklyDoughClosings_LeftoverMixedLoads_NonNegative", "[LeftoverMixedLoads] >= 0");

                            t.HasCheckConstraint("CK_WeeklyDoughClosings_LeftoverReadyBalls_NonNegative", "[LeftoverReadyBalls] >= 0");

                            t.HasCheckConstraint("CK_WeeklyDoughClosings_LostBalls_NonNegative", "[LostBalls] >= 0");

                            t.HasCheckConstraint("CK_WeeklyDoughClosings_NeededBalls_NonNegative", "[NeededBalls] >= 0");

                            t.HasCheckConstraint("CK_WeeklyDoughClosings_ProducedBalls_NonNegative", "[ProducedBalls] >= 0");

                            t.HasCheckConstraint("CK_WeeklyDoughClosings_UsedBalls_NonNegative", "[UsedBalls] >= 0");

                            t.HasCheckConstraint("CK_WeeklyDoughClosings_WeekWindow", "DATEDIFF(day, [WeekStartDate], [WeekEndDate]) = 6 AND (DATEDIFF(day, CONVERT(date, '19000101'), [WeekStartDate]) % 7) = 0 AND (DATEDIFF(day, CONVERT(date, '19000107'), [WeekEndDate]) % 7) = 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DailyDoughClosing", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CorrectedByUser")
                        .WithMany()
                        .HasForeignKey("CorrectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClosedByUser");

                    b.Navigation("CorrectedByUser");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughBatchQualityRecord", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.PrepTask", "OriginalDoughTask")
                        .WithMany()
                        .HasForeignKey("OriginalDoughTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParlorPrediction.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("OriginalDoughTask");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughLossRecord", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.DoughBatchQualityRecord", "DoughBatchQualityRecord")
                        .WithMany("LossRecords")
                        .HasForeignKey("DoughBatchQualityRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("DoughBatchQualityRecord");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughReballRecord", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.DoughBatchQualityRecord", "DoughBatchQualityRecord")
                        .WithMany("ReballRecords")
                        .HasForeignKey("DoughBatchQualityRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("DoughBatchQualityRecord");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughUsageTrace", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.DoughBatchQualityRecord", "SourceDoughBatchQualityRecord")
                        .WithMany("UsageTraces")
                        .HasForeignKey("SourceDoughBatchQualityRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("SourceDoughBatchQualityRecord");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.ManagerPrepRecommendation", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.PrepItem", "PrepItem")
                        .WithMany()
                        .HasForeignKey("PrepItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PrepItem");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.PrepItem", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.PrepStation", "PrepStation")
                        .WithMany("Items")
                        .HasForeignKey("PrepStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrepStation");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.PrepTask", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParlorPrediction.Domain.Entities.DoughPrepRecommendation", "DoughPrepRecommendation")
                        .WithMany()
                        .HasForeignKey("DoughPrepRecommendationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParlorPrediction.Domain.Entities.PrepItem", "PrepItem")
                        .WithMany()
                        .HasForeignKey("PrepItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.PrepStation", "PrepStation")
                        .WithMany()
                        .HasForeignKey("PrepStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.DoughBatch", "SourceDoughBatch")
                        .WithMany()
                        .HasForeignKey("SourceDoughBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ParlorPrediction.Domain.Entities.PrepTask", "SourcePrepTask")
                        .WithMany()
                        .HasForeignKey("SourcePrepTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompletedByUser");

                    b.Navigation("DoughPrepRecommendation");

                    b.Navigation("PrepItem");

                    b.Navigation("PrepStation");

                    b.Navigation("SourceDoughBatch");

                    b.Navigation("SourcePrepTask");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.WeeklyDoughClosing", b =>
                {
                    b.HasOne("ParlorPrediction.Domain.Entities.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParlorPrediction.Domain.Entities.User", "CorrectedByUser")
                        .WithMany()
                        .HasForeignKey("CorrectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClosedByUser");

                    b.Navigation("CorrectedByUser");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.DoughBatchQualityRecord", b =>
                {
                    b.Navigation("LossRecords");

                    b.Navigation("ReballRecords");

                    b.Navigation("UsageTraces");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.PrepStation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ParlorPrediction.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
