using ParlorPrediction.Domain.Rules;

namespace ParlorPrediction.Mvc.Models.DoughClosing;

public sealed class WeeklyCloseThisWeekConfirmViewModel
{
    public DateOnly ReferenceDate { get; set; }

    public DateOnly ClosingWeekStartDate { get; set; }

    public DateOnly ClosingWeekEndDate { get; set; }

    public DateOnly ServiceStartDate { get; set; }

    public DateOnly ServiceEndDate { get; set; }

    public Guid? ExistingClosingId { get; set; }

    public int ClosedDaysCount { get; set; }

    public int ExpectedServiceDaysCount { get; set; } = 6;

    public int TotalForecastBalls { get; set; }

    public int TotalActualUsedBalls { get; set; }

    public int AccumulatedVariance { get; set; }

    public int AccumulatedSurplus { get; set; }

    public int AccumulatedShortage { get; set; }

    public int ProducedBalls { get; set; }

    public int LostBalls { get; set; }

    public int ReadyBallsToCarryForward { get; set; }

    public int AttentionBallsToCarryForward { get; set; }

    public int UseFirstBallsToCarryForward { get; set; }

    public int MixedLoadsToCarryForward { get; set; }

    public int MixedPotentialBallsToCarryForward { get; set; }

    public bool CanConfirmClose { get; set; }

    public bool HasOpenServiceDays => ClosedDaysCount < ExpectedServiceDaysCount;

    public string AutoGeneratedNotes => BuildAutoGeneratedNotes();

    public int TotalAttentionAndUseFirstBalls => AttentionBallsToCarryForward + UseFirstBallsToCarryForward;

    private string BuildAutoGeneratedNotes()
    {
        var summary = $"Closed for closing window {ClosingWeekStartDate:yyyy-MM-dd} to {ClosingWeekEndDate:yyyy-MM-dd} using service days {ServiceStartDate:yyyy-MM-dd} to {ServiceEndDate:yyyy-MM-dd}.";
        var carryover = $" Carryover ready: {ReadyBallsToCarryForward}. Attention: {AttentionBallsToCarryForward}. Use First: {UseFirstBallsToCarryForward}.";
        var mixed = $" Mixed loads: {MixedLoadsToCarryForward} ({MixedPotentialBallsToCarryForward} potential balls).";
        return summary + carryover + mixed;
    }

    public int ReadyLoadsToCarryForward => ToLoads(ReadyBallsToCarryForward);

    public int AttentionLoadsToCarryForward => ToLoads(AttentionBallsToCarryForward);

    public int UseFirstLoadsToCarryForward => ToLoads(UseFirstBallsToCarryForward);

    public int MixedPotentialLoadsToCarryForward => ToLoads(MixedPotentialBallsToCarryForward);

    private static int ToLoads(int balls)
    {
        return balls <= 0
            ? 0
            : (int)Math.Ceiling(balls / (double)DoughRules.StandardBatchBalls);
    }
}
